apiVersion: v1
kind: Service
metadata:
  name: chat-and-social-features
  labels:
    app: chat-and-social-features
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: chat-and-social-features