---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-and-authentication
  labels:
    app: user-management-and-authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management-and-authentication
  template:
    metadata:
      labels:
        app: user-management-and-authentication
    spec:
      containers:
        - name: user-management-and-authentication
          image: username/user-management-and-authentication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-management
  labels:
    app: profile-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-management
  template:
    metadata:
      labels:
        app: profile-management
    spec:
      containers:
        - name: profile-management
          image: username/profile-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-and-recommendation
  labels:
    app: matching-and-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-and-recommendation
  template:
    metadata:
      labels:
        app: matching-and-recommendation
    spec:
      containers:
        - name: matching-and-recommendation
          image: username/matching-and-recommendation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-and-social-features
  labels:
    app: chat-and-social-features
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-and-social-features
  template:
    metadata:
      labels:
        app: chat-and-social-features
    spec:
      containers:
        - name: chat-and-social-features
          image: username/chat-and-social-features:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-based-service-management
  labels:
    app: location-based-service-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-based-service-management
  template:
    metadata:
      labels:
        app: location-based-service-management
    spec:
      containers:
        - name: location-based-service-management
          image: username/location-based-service-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: user-management-and-authentication
  labels:
    app: user-management-and-authentication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-management-and-authentication


---


apiVersion: v1
kind: Service
metadata:
  name: profile-management
  labels:
    app: profile-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: profile-management


---


apiVersion: v1
kind: Service
metadata:
  name: matching-and-recommendation
  labels:
    app: matching-and-recommendation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: matching-and-recommendation


---


apiVersion: v1
kind: Service
metadata:
  name: chat-and-social-features
  labels:
    app: chat-and-social-features
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: chat-and-social-features


---


apiVersion: v1
kind: Service
metadata:
  name: location-based-service-management
  labels:
    app: location-based-service-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: location-based-service-management

