apiVersion: v1
kind: Service
metadata:
  name: matching-and-recommendation
  labels:
    app: matching-and-recommendation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: matching-and-recommendation